import { Currency } from "@/global.types";

export const currencyList: Currency[] = [
	{
		name: "Nigerian Naira",
		code: "NGN",
		sign: "₦",
		country: "Nigeria",
		flag: "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg",
	},
	{
		name: "United States Dollar",
		code: "USD",
		sign: "$",
		country: "United States",
		flag: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
	},
	// {
	// 	name: "Euro",
	// 	code: "EUR",
	// sign: "",
	// 	country: "European Union",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg",
	// },
	// {
	// 	name: "Japanese Yen",
	// 	code: "JPY",
	// sign: "",
	// 	country: "Japan",
	// 	flag: "https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg",
	// },
	// {
	// 	name: "British Pound Sterling",
	// 	code: "GBP",
	// sign: "",
	// 	country: "United Kingdom",
	// 	flag: "https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg",
	// },
	// {
	// 	name: "Australian Dollar",
	// 	code: "AUD",
	// sign: "",
	// 	country: "Australia",
	// 	flag: "https://upload.wikimedia.org/wikipedia/en/b/b9/Flag_of_Australia.svg",
	// },
	// {
	// 	name: "Canadian Dollar",
	// 	code: "CAD",
	// sign: "",
	// 	country: "Canada",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Canada.svg",
	// },
	// {
	// 	name: "Swiss Franc",
	// 	code: "CHF",
	// sign: "",
	// 	country: "Switzerland",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg",
	// },
	// {
	// 	name: "Chinese Yuan",
	// 	code: "CNY",
	// sign: "",
	// 	country: "China",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg",
	// },
	// {
	// 	name: "Swedish Krona",
	// 	code: "SEK",
	// sign: "",
	// 	country: "Sweden",
	// 	flag: "https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg",
	// },
	// {
	// 	name: "New Zealand Dollar",
	// 	code: "NZD",
	// sign: "",
	// 	country: "New Zealand",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg",
	// },
	// {
	// 	name: "Mexican Peso",
	// 	code: "MXN",
	// sign: "",
	// 	country: "Mexico",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg",
	// },
	// {
	// 	name: "Singapore Dollar",
	// 	code: "SGD",
	// sign: "",
	// 	country: "Singapore",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg",
	// },
	// {
	// 	name: "Hong Kong Dollar",
	// 	code: "HKD",
	// sign: "",
	// 	country: "Hong Kong",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Hong_Kong.svg",
	// },
	// {
	// 	name: "Norwegian Krone",
	// 	code: "NOK",
	// sign: "",
	// 	country: "Norway",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg",
	// },
	// {
	// 	name: "South Korean Won",
	// 	code: "KRW",
	// sign: "",
	// 	country: "South Korea",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg",
	// },
	// {
	// 	name: "Turkish Lira",
	// 	code: "TRY",
	// sign: "",
	// 	country: "Turkey",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
	// },
	// {
	// 	name: "Indian Rupee",
	// 	code: "INR",
	// sign: "",
	// 	country: "India",
	// 	flag: "https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg",
	// },
	// {
	// 	name: "Russian Ruble",
	// 	code: "RUB",
	// sign: "",
	// 	country: "Russia",
	// 	flag: "https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg",
	// },
	// {
	// 	name: "Brazilian Real",
	// 	code: "BRL",
	// sign: "",
	// 	country: "Brazil",
	// 	flag: "https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg",
	// },
	// {
	// 	name: "South African Rand",
	// 	code: "ZAR",
	// sign: "",
	// 	country: "South Africa",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg",
	// },
	// {
	// 	name: "Saudi Riyal",
	// 	code: "SAR",
	// sign: "",
	// 	country: "Saudi Arabia",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg",
	// },
	// {
	// 	name: "United Arab Emirates Dirham",
	// 	code: "AED",
	// sign: "",
	// 	country: "United Arab Emirates",
	// 	flag: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg",
	// },
];
