import { FORM_FIELDS } from "@/components/ui/form-input/form.types";

export const formFields: FORM_FIELDS[] = [
  {
    name: "first_name",
    type: "text",
    label: "First Name",
    placeholder: "enter first name",
    required: false,
    readOnly: true,
    containerStyle: "col-span-2 lg:col-span-1",
  },
  {
    name: "last_name",
    type: "text",
    label: "Last Name",
    placeholder: "Enter last name",
    required: false,
    readOnly: true,
    containerStyle: "col-span-2 lg:col-span-1",
  },
  {
    name: "middle_name",
    type: "text",
    label: "Middle Name",
    placeholder: "Enter middle name",
    required: true,
    containerStyle: "col-span-2",
  },
  {
    name: "phone_number",
    type: "tel",
    label: "Phone number",
    placeholder: "",
    containerStyle: "col-span-2",
    required: false,
    readOnly: true,
  },
  {
    name: "username",
    type: "text",
    label: "Username",
    placeholder: "enter username",
    containerStyle: "col-span-2",
    required: true,
  },
  {
    name: "email",
    type: "text",
    label: "Email",
    placeholder: "enter Email",
    containerStyle: "col-span-2",
    required: false,
    readOnly: true,
  },
  {
    name: "date_of_birth",
    type: "date",
    label: "Date of Birth",
    containerStyle: "col-span-2 [&_input]:!w-full",
    placeholder: "",
    readOnly: true,
    required: false,
  },
  {
    name: "gender",
    type: "select",
    label: "gender",
    placeholder: "select Gender",
    containerStyle: "col-span-2",
    options: [
      { title: "male", value: "male" },
      { title: "female", value: "female" },
    ],
    readOnly: true,
    required: false,
  },
  {
    name: "address",
    type: "text",
    label: "Residential Address",
    placeholder: "Residential Address",
    containerStyle: "col-span-2",
    required: false,
    readOnly: true,
  },
  // {
  // 	name: "occupation",
  // 	type: "text",
  // 	label: "occupation",
  // 	placeholder: "Enter occupation",
  // 	containerStyle: "col-span-2",
  // 	required: true,
  // },
  // {
  // 	name: "income_level",
  // 	type: "text",
  // 	label: "Income Level",
  // 	placeholder: "Enter Income Level",
  // 	containerStyle: "col-span-2",
  // 	required: false,
  // },
  // {
  // 	name: "referred_by",
  // 	type: "text",
  // 	label: "Income Level",
  // 	placeholder: "Enter Income Level",
  //     required: false,
  //     readOnly: true
  // },
  // {
  //   name: "referral_code",
  //   type: "text",
  //   label: "Referral Code",
  //   placeholder: "",
  //   containerStyle: "col-span-2",
  //   required: false,
  //   readOnly: true,
  // },
];

